Basic:
  label: åŸºæœ¬è®¾ç½®
  items:
    bannerUrl:
      name: bannerUrl
      label: åšå®¢å¤´å›¾
      type: attachment
      default: /themes/0vcards/source/images/banner.jpg
      description: "ç”¨äºå±•ç¤ºå¤´å›¾"
    author_describe:
      name: author_describe
      label: åšä¸»ä¸€è¨€
      type: text
      default: 'ä¸Šå±±æ‰“è€è™ğŸ…'
      description: "å±•ç¤ºåœ¨åšä¸»æ˜µç§°ä¸‹é¢"
    preloader:
      name: preloader
      label: æ˜¯å¦å¼€å¯é¡µé¢é¢„åŠ è½½
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: å¼€å¯
        - value: false
          label: å…³é—­
    ScrollIndicator:
      name: ScrollIndicator
      label: æ˜¯å¦å¼€å¯é¡¶éƒ¨æ»šåŠ¨è¿›åº¦æ¡
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: å¼€å¯
        - value: false
          label: å…³é—­
    photos:
      name: photos
      label: ç›¸å†Œæ’åˆ—æ–¹å¼
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: å¹¶æ’
        - value: false
          label: ç€‘å¸ƒæµ
    links_random:
      name: links_random
      label: æ˜¯å¦å¼€å¯å‹é“¾éšæœºæ’åº
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: å¼€å¯
        - value: false
          label: å…³é—­
    pjax:
      name: pjax
      label: æ˜¯å¦å¼€å¯pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: å¼€å¯
        - value: false
          label: å…³é—­
    pjaxcomplete:
      name: pjaxcomplete
      label: pjaxå›è°ƒ
      type: textarea
      placeholder: "è¯·å¡«å†™pjaxå›è°ƒä»£ç "
    code_theme:
      name: code_theme
      label: æ–‡ç« é«˜äº®ä»£ç ä¸»é¢˜
      type: select
      data-type: string
      default: "one-dark"
      description: "è®¾ç½®ä»£ç å—ä¸»é¢˜ï¼Œå¯é€šè¿‡åå°å…ƒæ•°æ®ä¸ºæ¯ç¯‡æ–‡ç« è®¾ç½®å•ç‹¬çš„ä»£ç ä¸»é¢˜ï¼Œä¸»é¢˜æ¥è‡ª prism-themesï¼Œè§https://github.com/PrismJS/prism-themes"
      options:
        - value: "one-dark"
          label: "one-dark"
        - value: "one-light"
          label: "one-light"
        - value: "a11y-dark"
          label: "a11y-dark"
        - value: "atom-dark"
          label: "atom-dark"
        - value: "base16-ateliersulphurpool.light"
          label: "base16-ateliersulphurpool.light"
        - value: "cb"
          label: "cb"
        - value: "coldark-cold"
          label: "coldark-cold"
        - value: "coldark-dark"
          label: "coldark-dark"
        - value: "coy-without-shadows"
          label: "coy-without-shadows"
        - value: "darcula"
          label: "darcula"
        - value: "dracula"
          label: "dracula"
        - value: "duotone-dark"
          label: "duotone-dark"
        - value: "duotone-earth"
          label: "duotone-earth"
        - value: "duotone-forest"
          label: "duotone-forest"
        - value: "duotone-light"
          label: "duotone-light"
        - value: "duotone-sea"
          label: "duotone-sea"
        - value: "duotone-space"
          label: "duotone-space"
        - value: "ghcolors"
          label: "ghcolors"
        - value: "gruvbox-dark"
          label: "gruvbox-dark"
        - value: "gruvbox-light"
          label: "gruvbox-light"
        - value: "holi-theme"
          label: "holi-theme"
        - value: "hopscotch"
          label: "hopscotch"
        - value: "lucario"
          label: "lucario"
        - value: "material-dark"
          label: "material-dark"
        - value: "material-light"
          label: "material-light"
        - value: "material-oceanic"
          label: "material-oceanic"
        - value: "night-owl"
          label: "night-owl"
        - value: "nord"
          label: "nord"
        - value: "pojoaque"
          label: "pojoaque"
        - value: "shades-of-purple"
          label: "shades-of-purple"
        - value: "solarized-dark-atom"
          label: "solarized-dark-atom"
        - value: "synthwave84"
          label: "synthwave84"
        - value: "vs"
          label: "vs"
        - value: "vsc-dark-plus"
          label: "vsc-dark-plus"
        - value: "xonokai"
          label: "xonokai"
        - value: "z-touch"
          label: "z-touch"
    icp:
      name: icp
      label: ICP å¤‡æ¡ˆå·
      type: text
      default: ""
      placeholder: "è¯·å¡«å†™ ICP å¤‡æ¡ˆå·ä¿¡æ¯"
      description: "ICP å¤‡æ¡ˆä¿¡æ¯å°†å±•ç¤ºåœ¨é¡µè„šä¸­ï¼Œä¸å¡«ä¸å±•ç¤ºï¼ˆç¤ºä¾‹ï¼šæ»‡ICPå¤‡xxå·ï¼‰"
Sns:
  label: ç¤¾äº¤èµ„æ–™
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: å¼€å¯
        - value: false
          label: å…³é—­
    qq:
      name: qq
      label: QQ
      type: text
      placeholder: 'åªéœ€å¡«å…¥ QQ å·å³å¯'
    weibo:
      name: weibo
      label: å¾®åš
      type: text
      placeholder: 'åªéœ€å¡«å…¥å¾®åš Id å³å¯'
    email:
      name: email
      label: Email
      type: text
      placeholder: 'åªéœ€å¡«å…¥é‚®ç®±åœ°å€å³å¯'
    github:
      name: github
      label: Github
      type: text
      placeholder: 'åªéœ€å¡«å…¥ Github ç”¨æˆ·åå³å¯'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: 'åªéœ€å¡«å…¥ Telegram Id å³å¯'
    bilibili:
      name: bilibili
      label: Bilibili
      type: text
      placeholder: 'è¯·è¾“å…¥ä½ çš„bilibliç”¨æˆ·ä¸»é¡µé“¾æ¥'
style:
  label: æ ·å¼è®¾ç½®
  items:
    indexcolor:
      name: indexcolor
      label: ä¸»é¢˜ä¸»è‰²
      type: color
      default: '#3086FF'
    aidecolor:
      name: aidecolor
      label: ä¸»é¢˜è¾…åŠ©è‰²
      type: color
      default: '#FF965D'
    textcolor:
      name: textcolor
      label: æ–‡æœ¬é¢œè‰²
      type: color
      default: '#3B4B5E'
    DIYfonts:
      name: DIYfonts
      label: è‡ªå®šä¹‰å­—ä½“
      type: text
      default: '/themes/0vcards/source/fonts/OPPO-OS.woff2' 
      placeholder: 'è¾“å…¥ä½ çš„è‡ªå®šä¹‰å­—ä½“é“¾æ¥' 
    custom:
      name: custom
      label: è‡ªå®šä¹‰æ ·å¼
      type: textarea
      placeholder: 'ä¸éœ€è¦ <style></style> æ ‡ç­¾' 